name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fedora-build:
    name: fedora
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide

    steps:
    - uses: actions/checkout@v4
    - run: cat /etc/os-release
    - name: install dependencies
      run: |
       dnf -y copr enable fed500/haunt
       dnf -y update
       dnf --refresh -y install haunt guile-reader-devel guile-commonmark guile30-devel gcc diffutils awk autoconf automake make tar texinfo
    - name: build site
      run: haunt build
